title: Ren√© Gregory 
logo: /headshot_circle.png 
description: - A data-driven professional with passion for data engineering & analytics, currently working as Data Analyst. 
show_downloads: true 
theme: jekyll-theme-minimal
