title: Ren√© Gregory 
logo: /assets/img/headshot_circle.png 
css: "/style.css"
description: - A data-driven professional with passion for data engineering & analytics, currently working as Data Analyst. 
show_downloads: true 
theme: jekyll-theme-minimal
